Spanner - add NUMERIC type
spring-cloud/spring-cloud-gcp pull request #2518
Opened 2020-09-10 21:42 UTC by dmitry-s

fixes #2515

2020-09-10 22:37 UTC, meltsufin requested changes
Looks good overall!

Can you also update the sample where we use `Double price` to use `BigDecimal price`?

Looks like there is a compilation error in Firestore module now. Probably has to do with dep version changes.

2020-09-10 22:37 UTC, meltsufin commented on spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/convert/StructAccessor.java
> +				.put(BigDecimal.class, AbstractStructReader::getBigDecimal)
This looks like a duplicate of the above map, but there's probably some obscure reason for it. :)

2020-09-10 22:37 UTC, meltsufin commented on spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryTests.java
> +									+ "price>@tag10 AND price<=@tag11 AND price IN UNNEST(@tag12) "
`price` is actually a perfect field to use `BigDecimal` for.

2020-09-11 15:25 UTC, elefeint approved these changes
Couple of optional nits, LGTM.

2020-09-15 02:31 UTC, meltsufin requested changes
Looks good for Spanner, but can we do the Firestore fix in a separate PR please?

2020-09-15 02:31 UTC, meltsufin commented on spring-cloud-gcp-data-firestore/src/main/java/org/springframework/cloud/gcp/data/firestore/util/Util.java
> +		//the parent looks like this: projects/{project_id}/databases/{database_id}/...
This is unrelated. Can we please put it in a separate PR?

2020-09-16 01:23 UTC, meltsufin approved these changes

2020-09-16 11:57 UTC, elefeint approved these changes

2020-09-16 13:58 UTC, merged