Firestore - switch to commit to avoid write limitations
spring-cloud/spring-cloud-gcp pull request #2600
Opened 2020-11-19 17:41 UTC by dmitry-s

fixes #2561 
fixes #2574

2020-11-19 19:35 UTC, meltsufin requested changes
Have you compared the performance difference?

2020-11-19 19:35 UTC, meltsufin commented on spring-cloud-gcp-data-firestore/src/main/java/org/springframework/cloud/gcp/data/firestore/FirestoreTemplate.java
> +			return Flux.from(instances).bufferTimeout(this.writeBufferSize, this.writeBufferTimeout)
Can we de-dup this and the block in `deleteDocumentsByName()` by wrapping `builder.addWrites(createUpdateWrite(e))` into a lambda?

2020-11-19 22:18 UTC, dmitry-s commented
@meltsufin there is actually nothing to compare, the old way was unable to write more than a couple of thousands - that's why I thought it was faster.

2020-11-19 22:19 UTC, meltsufin approved these changes

2020-11-20 14:20 UTC, elefeint approved these changes

2020-11-24 00:43 UTC, merged